package com.whosaiddonut.service

data class CreditReportInfo(val score: Int = 0,
        val scoreBand: Int = 0,
        val clientRef: String = "",
        val status: String = "",
        val maxScoreValue: Int = 700,
        val minScoreValue: Int = 0,
        val monthsSinceLastDefaulted: Int = 0,
        val hasEverDefaulted: Boolean = false,
        val monthsSinceLastDelinquent: Int = 0,
        val hasEverBeenDelinquent: Boolean = false,
        val percentageCreditUsed: Int = 0,
        val percentageCreditUsedDirectionFlag: Int = 0,
        val changedScore: Int = 0,
        val currentShortTermDebt: Int = 0,
        val currentShortTermNonPromotionalDebt: Int = 0,
        val currentShortTermCreditLimit: Int = 0,
        val currentShortTermCreditUtilisation: Int = 0,
        val changeInShortTermDebt: Int = 0,
        val currentLongTermDebt: Int = 0,
        val currentLongTermNonPromotionalDebt: Int = 0,
        val currentLongTermCreditLimit: Int?,
        val currentLongTermCreditUtilisation: Int?,
        val changeInLongTermDebt: Int = 0,
        val numPositiveScoreFactors: Int = 0,
        val numNegativeScoreFactors: Int = 0,
        val equifaxScoreBand: Int = 0,
        val equifaxScoreBandDescription: String = "",
        val daysUntilNextReport: Int = 0
)